const mongoose = require('mongoose');

// Define the schema for the Report
const reportSchema = new mongoose.Schema({
    sto_co: String,
    kabupaten: String,
    cluster: String,
    branch: String,
    wok: String,
    region: String,
    area: String,
    order_id: String,
    package_type: String,
    order_type: String,
    order_mode: String,
    order_initiator_id: String,
    order_initiator_id_type: String,
    process_state: String,
    provi_group: String,
    provi_subgroup: String,
    funneling_group: String,
    funneling_subgroup: String,
    provi_ts: String,
    provi_duration: String,
    name: String,
    no_handphone: String,
    segmentation: String,
    order_ts: String,
    io_ts: String,
    re_ts: String,
    ps_ts: String,
    completed_ts: String,
    order_channel: String,
    channel_name: String,
    channel_group: String,
    service_id: String,
    product_id_co: String,
    product_commercial_name: String,
    package_cat: String,
    order_subtype: String,
    order_status: String,
    order_status_desc: String,
    payment_method: String,
    order_amount: String,
    tgl_manja: String,
    detail_manja: String,
    prev_state: String,
    prev_state_ts: String,
    longitude: String,
    latitude: String,
    appointment_id: String,
    appointment_start: String,
    appointment_end: String,
    reservation_id_odp: String,
    c_wonum: String,
    c_actstart: String,
    c_actfinish: String,
    c_errorcode: String,
    c_suberrorcode: String,
    c_engineermemo: String,
    c_urlevidence: String,
    c_amcrew: String,
    last_update: String,
    customer_account_id: String,
    channel_transaction_id: String,
    order_type_id: String,
    sf_code: String,
    sf_name: String,
    sf_contact_number: String,
    sf_email: String,
    sf_company_name: String,
    sf_branch_name: String,
    ro_ts: String,
    pi_ts: String,
    pc_ts: String,
    odp_name: String,
    subchannel: String,
    referral_code: String,
    product_type: String,
    fallout_source: String,
    fallout_category: String,
    fallout_subcategory: String,
    product_id_orbit: String,
    sla_duration: String,
    event_date: String,
    address: String,
    c_chief_code: String,
    c_chief_name: String,
    fallout_reason: String,
    fiber_provisioning_type: String,
    cancel_category: String,
    cancel_reason: String
}, { collection: 'reports' });

// Create the model from the schema
const Report = mongoose.model('Report', reportSchema);

module.exports = Report;
